# Generated by Django 3.0.1 on 2020-03-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('Grade', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Section', models.CharField(max_length=1000)),
            ],
        ),
    ]
