# Generated by Django 3.0.1 on 2020-03-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='Grade',
            field=models.PositiveIntegerField(),
        ),
    ]
