# Generated by Django 3.0.1 on 2020-03-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_auto_20200331_1239'),
    ]


