# Generated by Django 3.0.1 on 2020-03-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_grade_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='Grade',
        )
    ]
