# Generated by Django 3.0.1 on 2020-03-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_auto_20200331_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='Grade',
            field=models.PositiveIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
