# Generated by Django 3.0.1 on 2020-03-31 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0005_auto_20200331_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_grade', models.PositiveIntegerField()),
                ('section', models.PositiveIntegerField()),
                ('Student_id', models.PositiveIntegerField()),
                ('Link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costs.grade')),
            ],
        ),
    ]
