# Generated by Django 3.0.1 on 2020-03-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0007_student_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
