# Generated by Django 3.0.1 on 2020-03-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0009_auto_20200331_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='Teacher1',
            field=models.CharField(default='f', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='Teacher2',
            field=models.CharField(default='f', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='email_1',
            field=models.EmailField(default='f@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='email_2',
            field=models.EmailField(default='f@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
