# Generated by Django 3.0.1 on 2020-03-30 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('ISBN', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('Ind_Book_ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=1000)),
                ('student_id', models.PositiveIntegerField()),
                ('issue_date', models.DateField()),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.books')),
            ],
        ),
        migrations.CreateModel(
            name='book_ind',
            fields=[
                ('Ind_Book_ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.books')),
            ],
        ),
    ]
