# Generated by Django 3.0.1 on 2020-03-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='return_date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
