# Generated by Django 3.0.1 on 2020-03-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_issues_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_ind',
            name='Name',
            field=models.PositiveIntegerField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
