# Generated by Django 3.0.1 on 2020-03-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_book_ind_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_ind',
            name='Name',
            field=models.CharField(max_length=1000),
        ),
    ]
