# Generated by Django 3.0.1 on 2020-03-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_late_dues'),
    ]

    operations = [
        migrations.AddField(
            model_name='late_dues',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
