# Generated by Django 3.0.1 on 2020-03-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_late_dues_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='late_dues',
            name='Name',
            field=models.CharField(default='qew', max_length=1000),
            preserve_default=False,
        ),
    ]
